spring:
  flyway:
    locations:
      - classpath:db/migration
      - classpath:db/devdata

  jpa:
    properties:
      hibernate:
        format_sql: true

  datasource:
    username: file-uploader-application
    password: postgres
    url: jdbc:postgresql://localhost:5432/file-uploader

file-uploader:
  properties:
    maxFileUploadSize: 512KB
  keycloak:
    enabled: true
    # could be list of keycloak urls
    urls: http://localhost:8081/realms/fileupload

