name: release-exists
description: Utility to fail if deploy release missing or subcomponent already defined.

inputs:
  githubToken:
    description: token to access Github
    required: true
  releaseVersion:
    description: 'Release number, like 3.0.1-alpha'
    required: true
  component:
    description: 'Either frontend, backend, or deploy'
    required: true

runs:
  using: composite
  steps:
    - name: Validate version
      shell: bash
      env:
        RELEASE_VERSION: ${{ inputs.releaseVersion }}
      run: |
        # validate version, like 1.2.3-dev
        rx='^([0-9]+\.){2}(\*|[0-9]+)(-.*)?$'
        if ! [[ ${RELEASE_VERSION} =~ $rx ]]; then
        echo "ERROR: Invalid version number format: ${RELEASE_VERSION}"
          exit 1
        fi

    - name: Check parent release not exists
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}
        RELEASE_VERSION: v${{ inputs.releaseVersion }}
        COMPONENT: ${{ inputs.component }}
      run: |
        .github/workflows/deploy-release-exists/deploy_release_exists.sh
