# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI

on:
  push:
    branches:
      - 'master'
      - 'feature**'
  pull_request:
    branches:
      - '**'
    types: [ opened, synchronize ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        uses: ./.github/workflows/run-tests

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Run build
        uses: ./.github/workflows/run-build

      - name: Create dev container image
        uses: ./.github/workflows/create-dev-container-image
        with:
          githubToken: ${{ secrets.DEVOPS_TOKEN }}
          component: backend


  deploy-dev:
    if: github.ref_name == 'develop'
    runs-on: ubuntu-20.04
    needs: [ build, test ]
    steps:
      - uses: actions/checkout@v3

      - name: Trigger dev deployment
        uses: ./.github/workflows/trigger-dev-deployment
        with:
          githubToken: ${{ secrets.DEVOPS_TOKEN }}
          environment: dev
          frontendTag: develop-latest
          backendTag: develop-latest
